from odoo.exceptions import UserError


class OdooSaaSClientResourceException(UserError):
    pass
